apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: default
type: Opaque
data:
  MONGODB_INITDB_ROOT_USERNAME: bXlhcHB1c2Vy # base64 encoded
  MONGODB_INITDB_ROOT_PASSWORD: bXBhcHBwd2Q= # base64 encoded
  SECRET_KEY: c2VjcmV0MTIzCg== # base64 encoded