apiVersion: apps/v1
kind: Deployment
metadata:
  name: wiz-webserver-deployment
  labels:
    app: tasky
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tasky
  template:
    metadata:
      labels:
        app: tasky
    spec:
      containers:
      - name: tasky-webserver
        image: mcpsgithub/todo-on-minikube:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: wiz-webserver-service
spec:
  type: NodePort
  selector:
    app: tasky
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 8080
      nodePort: 30100