apiVersion: apps/v1
kind: Deployment
metadata:
  name: wiz-webserver-deployment
  labels:
    app: tasky
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tasky
  template:
    metadata:
      labels:
        app: tasky
    spec:
      containers:
      - name: tasky-webserver
        image: 017820672665.dkr.ecr.us-east-2.amazonaws.com/wiz-technical-assessment:latest
        ports:
        - containerPort: 8080
        env:
        - name: USER_NAME
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: mongo-username
        - name: USER_PWD
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: mongo-password
        - name: DB_URL
          valueFrom:
            configMapKeyRef:
              name: mongodb-config
              key: mongo-url 
        - name: secret-key
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: secret-key
   
   #   - name: MONGODB_URI
   #     value: 'mongodb://$(MONGODB_USER):$(MONGODB_PASS)@$(MONGODB_HOST):$(MONGODB_PORT)/$(MONGODB_DB)?authSource=$(MONGODB_DB)'
---
apiVersion: v1
kind: Service
metadata:
  name: wiz-webserver-service
spec:
  type: NodePort
  selector:
    app: tasky
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 8080
      nodePort: 30100