apiVersion: apps/v1
kind: Deployment
metadata:
  name: wiz-webserver-deployment
  labels:
    app: tasky
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tasky
  template:
    metadata:
      labels:
        app: tasky
    spec:
      containers:
      - name: tasky-webserver
        image: McPsGitHub/todo-on-minikube:latest
        ports:
        - containerPort: 8080
        env:
        - name: MONGODB_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: MONGODB_INITDB_ROOT_USERNAME
        - name: MONGODB_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: MONGODB_INITDB_ROOT_PASSWORD
        - name: DB_URL
          valueFrom:
            configMapKeyRef:
              name: mongodb-config
              key: mongo-url 
        - name: SECRET-KEY
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: SECRET-KEY
        - name: MONGODB_URI
          value: 'mongodb://$(MONGODB_USER):$(MONGODB_PASS)@$(MONGODB_HOST):$(MONGODB_PORT)/$(MONGODB_DB)?authSource=$(MONGODB_DB)'
---
apiVersion: v1
kind: Service
metadata:
  name: wiz-webserver-service
spec:
  type: NodePort
  selector:
    app: tasky
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 8080
      nodePort: 30100